# Source - https://stackoverflow.com/a/66514770
# Posted by Fonsito
# Retrieved 2026-02-10, License - CC BY-SA 4.0

services:
  db:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=draw2
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      mongo-compose-network:
        aliases:
          - mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - db
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
    ports:
      - '8081:8081'

networks:
  mongo-compose-network:
    driver: bridge
